In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

In [2]:
cars= pd.read_csv("Cars.csv")

In [3]:
cars.head()

   HP        MPG  VOL          SP         WT
0  49  53.700681   89  104.185353  28.762059
1  55  50.013401   92  105.461264  30.466833
2  55  50.013401   92  105.461264  30.193597
3  70  45.696322   92  113.461264  30.632114
4  53  50.504232   92  104.461264  29.889149

In [4]:
cars.tail()

     HP        MPG  VOL          SP         WT
76  322  36.900000   50  169.598513  16.132947
77  238  19.197888  115  150.576579  37.923113
78  263  34.000000   50  151.598513  15.769625
79  295  19.833733  119  167.944460  39.423099
80  236  12.101263  107  139.840817  34.948615

In [5]:
cars.describe()

               HP        MPG         VOL          SP         WT
count   81.000000  81.000000   81.000000   81.000000  81.000000
mean   117.469136  34.422076   98.765432  121.540272  32.412577
std     57.113502   9.131445   22.301497   14.181432   7.492813
min     49.000000  12.101263   50.000000   99.564907  15.712859
25%     84.000000  27.856252   89.000000  113.829145  29.591768
50%    100.000000  35.152727  101.000000  118.208698  32.734518
75%    140.000000  39.531633  113.000000  126.404312  37.392524
max    322.000000  53.700681  160.000000  169.598513  52.997752

In [6]:
cars.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 81 entries, 0 to 80
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   HP      81 non-null     int64
 1   MPG     81 non-null     float64
 2   VOL     81 non-null     int64
 3   SP      81 non-null     float64
 4   WT      81 non-null     float64
dtypes: float64(3), int64(2)
memory usage: 3.3 KB

In [7]:
cars.corr()

           HP       MPG       VOL        SP        WT
HP   1.000000 -0.725038  0.077459  0.973848  0.076513
MPG -0.725038  1.000000 -0.529057 -0.687125 -0.526759
VOL  0.077459 -0.529057  1.000000  0.102170  0.999203
SP   0.973848 -0.687125  0.102170  1.000000  0.102439
WT   0.076513 -0.526759  0.999203  0.102439  1.000000

In [8]:
cars.shape

(81, 5)

In [9]:
%pip install scikit-learn

Requirement already satisfied: scikit-learn in /opt/anaconda3/lib/python3.13/site-packages (1.6.1)
Requirement already satisfied: numpy>=1.19.5 in /opt/anaconda3/lib/python3.13/site-packages (from scikit-learn) (2.1.3)
Requirement already satisfied: scipy>=1.6.0 in /opt/anaconda3/lib/python3.13/site-packages (from scikit-learn) (1.15.3)
Requirement already satisfied: joblib>=1.2.0 in /opt/anaconda3/lib/python3.13/site-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /opt/anaconda3/lib/python3.13/site-packages (from scikit-learn) (3.5.0)

[notice] A new release of pip is available: 25.1.1 -> 26.2.2
[notice] To update, run: pip3 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
x = cars.iloc[:, [0, 2, 3, 4]] 
y = cars.iloc[:, 1]

In [12]:
print(x)

     HP  VOL          SP         WT
0    49   89  104.185353  28.762059
1    55   92  105.461264  30.466833
2    55   92  105.461264  30.193597
3    70   92  113.461264  30.632114
4    53   92  104.461264  29.889149
..  ...  ...         ...        ...
76  322   50  169.598513  16.132947
77  238  115  150.576579  37.923113
78  263   50  151.598513  15.769625
79  295  119  167.944460  39.423099
80  236  107  139.840817  34.948615

[81 rows x 4 columns]

In [13]:
print(y)

0     53.700681
1     50.013401
2     50.013401
3     45.696322
4     50.504232
        ...
76    36.900000
77    19.197888
78    34.000000
79    19.833733
80    12.101263
Name: MPG, Length: 81, dtype: float64

In [14]:
X_train, X_test, y_train, y_test = train_test_split(x,y,test_size=0.2)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((64, 4), (17, 4), (64,), (17,))

In [15]:
from sklearn.linear_model import LinearRegression

In [16]:
model=LinearRegression()

In [17]:
model.fit(X_train,y_train)

LinearRegression()

In [18]:
tr_predicted=model.predict(X_train)

In [19]:
tr_predicted

array([30.29432927, 39.14567721, 49.16245703, 24.66377979, 37.38647886,
       33.9660825 , 41.57751652, 24.63798503, 34.68361716, 43.0814863 ,
       34.30543841, 38.97073607, 41.40526551, 35.27330909, 40.97519769,
       41.21049378, 19.2220225 , 32.75206436, 24.98396396, 42.83621805,
       35.81119565, 22.7644406 , 34.86649514, 14.82822014, 37.28826791,
       36.74139845, 26.02723626, 20.81016837, 38.36393974, 41.55737739,
       41.35520681, 38.44553985, 23.22324759, 37.53601401, 33.69318752,
       31.59425543, 28.56588626, 47.80127468, 25.744738  , 38.02265184,
       15.51335507, 36.06592457, 32.8441356 , 41.26103868, 47.73619425,
       23.93963018, 28.64462142, 26.29149632, 47.48765616, 22.57678848,
       32.84136815, 49.10642389, 36.2275401 , 41.54276675, 34.87198143,
       41.28979249, 29.22019778, 40.68852274, 42.56557706, 39.03565043,
       36.9862736 , 36.70005466, 34.90487651, 38.16593491])

In [20]:
from sklearn.metrics import mean_absolute_error,r2_score
from sklearn.metrics import mean_squared_error
import numpy as np

In [21]:
train_mae = mean_absolute_error(y_train, tr_predicted)

train_mse = mean_squared_error(y_train, tr_predicted)

train_rmse = np.sqrt(train_mse)

In [22]:
test_predicted=model.predict(X_train)

In [23]:
r2 = r2_score(y_train, test_predicted)

In [24]:
r2

0.7711998820560342

In [25]:
test_predicted = model.predict(X_test)

In [26]:
r2 = r2_score(y_test, test_predicted)

In [27]:
r2

0.7038073750921843